export const installationProjects = [
  {
    id: 1,
    title: "Lockin S50M Pro Installation",
    suburb: "Adelaide",
    description: "Camera smart lock fitted beside an existing pull handle on an entry door.",
    image: "/img/products/lockin-s50m-pro/real-install-01.jpg",
    category: "S50M Pro",
    productSlug: "lockin-s50m-pro-smart-lock",
  },
  {
    id: 2,
    title: "Lockin V5 Max Installation",
    suburb: "Adelaide",
    description: "A full-size smart lock fitted to a residential entry door, with the existing door hardware retained where compatible.",
    image: "/img/products/lockin-v5-max/real-install-02.jpg",
    category: "V5 Max",
    productSlug: "lockin-v5-max-smart-lock",
  },
  {
    id: 3,
    title: "Lockin SV40 Installation",
    suburb: "Adelaide",
    description: "Slim smart lock fitted to a timber entry door, showing the finished handle and lock position.",
    image: "/img/products/lockin-sv40/real-install-03.jpg",
    category: "SV40",
    productSlug: "lockin-sv40-smart-lock",
  },
  {
    id: 4,
    title: "Lockin S6 Max Installation",
    suburb: "Adelaide",
    description: "A full-size smart lock fitted to a timber door after checking the available space and clearance.",
    image: "/img/products/lockin-s6-max/real-install-04.jpg",
    category: "S6 Max",
    productSlug: "lockin-s6-max-smart-lock",
  },
  {
    id: 5,
    title: "Lockin X9 Installation",
    suburb: "Adelaide",
    description: "A compact handle-style smart lock installed on a front door for everyday keyless entry.",
    image: "/img/products/lockin-x9/real-install-02.jpg",
    category: "X9",
    productSlug: "lockin-x9-smart-lock",
  },
  {
    id: 6,
    title: "Lockin OLA Slim Gate Installation",
    suburb: "Adelaide",
    description: "A slim handle-style lock fitted to a slatted timber gate. Gate suitability and exposure need to be checked for each installation.",
    image: "/img/products/lockin-ola-slim/real-install-gate.jpg",
    category: "OLA Slim",
    productSlug: "lockin-ola-slim-smart-lock",
  },
];
